[package]
name = "Inox"
version = "0.0.1"
authors = ["Dirk Van Haerenborgh <vhdirk@gmail.com>"]

[lib]
name = "inox_core"
path = "src/core/lib.rs"

[[bin]]
name = "inox-gtk"
path = "src/gtk/main.rs"


[dependencies]
clap = "*"
log = "*"
env_logger ="*"
shellexpand = "*"
net2 = "*"
nix = "*"
regex = "*"
toml = "*"
serde = "*"
serde_derive = "*"
serde_ini = "*"
lazy_static = "1.0"
vte = "0.3.2"
notmuch = "*"
chrono = { version = "0.4", features = ["serde"] }

gtk         = "^0.3.0"
cairo-rs    = "^0.3.0"
gdk         = "^0.7.0"
gdk-sys     = "^0.5.0"
gdk-pixbuf  = "^0.3.0"
gio         = "^0.3.0"
glib        = "^0.4.0"

lettre = "*"

[features]
default = ["gtk/v3_16"]
gtk_3_10 = ["gtk/v3_10"]
gtk_3_16 = ["gtk_3_10", "gtk/v3_16"]
gtk_3_18 = ["gtk_3_16", "gtk/v3_18"] #for CI tools
gtk_3_20 = ["gtk_3_18", "gtk/v3_20"] #for CI tools


[patch.crates-io]
notmuch = { path="../notmuch-rs" }
